team-joshua-and-ndubuisi/NeatFleet

- readme.md
Introduced a readme that contains best practices for git  AND your PRs.
Please read through it and try implementing it for best practices.
Note: 
- Tech Stack will need to be updated once we have it down
No test required, but please read through it and try implementing it from this point on to establish the habit of best practices.
> docs(readme): add initial README

- .github/pull_request_template.md
Introducing PR template, so that each PR's description consists of a template for you to work from.
Unable to test until this PR is merged.
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository
https://www.youtube.com/watch?v=MjsS4ujX3nU&ab_channel=KahanDataSolutions
> TJN-16 Introduce PR template

- .github/workflows/client.yaml
- .github/workflows/server.yaml
- client/.gitignore
- server/.gitignore
- server/package.json
- server/src/lib/generateKeyPair.ts
- server/src/lib/issueJWT.ts
- server/src/server.ts
- server/vercel.json
Fixed workflows and integrated vercel config file to enable deployment for the server.
> TJN-25: Deploy to Vercel and Implement CI/CD

- .github/pull_request_template.md
Deleted duplicate sentences from PR template
PR template works correctly, no need to test.
>  TJN-16 Delete duplicate sentences from PR-template

- server/README.md
- Created content for server dir README.  Considered best practice to have separate READMEs for client and server.
- Check out the README doc in the server dir.
- [Jira Link](https://yassahr.atlassian.net/jira/software/projects/TJN/boards/1?selectedIssue=TJN-16)
> Add content to server README

- client/README.md
- Implemented design system, covering typography, color palette, and icons to use to ensure a consistency
- Nothing to be tested
- [Jira Link](https://yassahr.atlassian.net/browse/TJN-20)
Inspiration from:
> TJN-20/design-system

- .gitignore
- .vscode/extensions.json
- .vscode/settings.json
- client/.gitignore
- client/.prettierignore
- client/.prettierrc
- client/README.md
- client/eslint.config.js
- client/package-lock.json
- client/package.json
- server/.prettierignore
- server/.prettierrc
- server/eslint.config.js
- server/package-lock.json
- server/package.json
Standardize code formatting across the team using Prettier to avoid unnecessary diffs and formatting inconsistencies in pull requests. This will ensure consistent indentation, quote usage, trailing commas, and other style rules, regardless of each developer’s local IDE settings.
We will add a Prettier config file to the project, integrate formatting commands into package.json.
- Make sure to set format on save to true
- Write some code with incorrect formatting (too many spaces, missing semi-colons, etc.), run the format command or hit save and watch the code clean itself
- [Jira Link](https://yassahr.atlassian.net/jira/software/projects/TJN/boards/1?selectedIssue=TJN-33)
> Tjn 33 create prettier config

- client/src/components/home/BusinessInfoCard.tsx
- client/src/components/home/HomeLayout.tsx
- client/src/data/homeInfoCards.ts
- client/src/data/index.ts
- client/src/data/socialLinks.ts
- client/src/pages/HomePage.tsx
-Created business info and social media links components and added import files to the data folder to dynamically load data for the components. The appointment button is currently linked to the About page and can be changed to the bookings page once created.
- Step 1: Navigate to the next link using the appointment button
- Step 2: Select the social media links
- [Jira Link: TJN-22](https://yassahr.atlassian.net/jira/software/projects/TJN/boards/1?selectedIssue=TJN-22)
> TJN-22: Complete Landing Page

- client/src/components/BackButton.tsx
- client/src/components/index.ts
- client/src/data/navItems.ts
- client/src/pages/CartPaymentPage.tsx
- client/src/pages/ManageSchedulePage.tsx
- client/src/pages/ManageServicesPage.tsx
- client/src/pages/ManageTechniciansPage.tsx
- client/src/pages/ProfilePage.tsx
- client/src/pages/RatingPage.tsx
- client/src/pages/ScheduleServicePage.tsx
- client/src/pages/ServiceCatalogPage.tsx
- client/src/pages/StatusPage.tsx
- client/src/pages/TechSelectionPage.tsx
- client/src/routes/routes.tsx
- Create client-side routing for pages based on the original wireframe.  These are just placeholder pages for now but there are components such as the BackButton that will be helpful in the future.
- NavBar should have Services and Profile link:
- Clicking the Services link should bring you to a dummy services-catalog (the only thing that is functional is the choose a technician link)
- clicking choose a technician takes you to the next page:
- Clicking on a technician takes you to the schedule page:
- Clicking the Proceed to payment takes you to the cart and checkout page (the id is the technician you selected):
- Back at the home page, clicking the Profile link takes you to the profile page:
- the type of user is hard-coded but the idea would be that we dynamically render the page based …
> TJN-23-feat/set-page-structure

- client/package-lock.json
- client/package.json
- client/src/components/technician/AvailableDayPicker.tsx
- client/src/components/technician/AvailableTimePicker.tsx
- client/src/components/technician/TechAvailabilityForm.tsx
- client/src/components/ui/toggle-group.tsx
- client/src/components/ui/toggle.tsx
- client/src/pages/LoginPage.tsx
- client/src/pages/SignupPage.tsx
- client/src/pages/technician/ManageAvailabilityPage.tsx
- add technician availability ui page components
- add shadcn components and dependencies
- add available day picker - select one or more days
- add available time picker - select one or more time slots available
- add techAvailability form - container for components
- add manageAvailability page - to handle display of route
- [ x ] New feature
- add route to router to display page in this case i used the /test route but did not commit it
- navigate to url and page will display component
- [ x ] No documentation changes required
- https://yassahr.atlassian.net/jira/software/projects/TJN/boards/1?selectedIssue=TJN-41
> Tjn 41 UI tech availability

- client/package-lock.json
- client/package.json
- client/src/components/NavBar.tsx
- client/src/components/ui/dropdown-menu.tsx
- client/src/components/ui/navigation-menu.tsx
- client/src/components/ui/sheet.tsx
- Added shadcn components to adjust navbar responsiveness
- Live preview: https://neatfleetclient-lhq967n0i-227faddis-projects.vercel.app/
https://github.com/user-attachments/assets/d75093ad-c874-4987-a19c-21526e682825
- [Jira Link](https://yassahr.atlassian.net/browse/TJN-46)
> TJN-46/responsiveness-navbar

- .github/workflows/client.yaml
- .github/workflows/server.yaml
- Improved pipeline by adding a if statement to check when to deploy on production and preview environments on vercel
- Add validation check for repository env variables
- Can only be tested once merged
- [Jira Link](https://yassahr.atlassian.net/browse/TJN-62)
> TJN-62/Adjust-CI/CD

- server/package.json
- server/src/app.ts
- server/src/config/limiter.ts
- server/src/config/logger.ts
- server/src/config/passport.ts
- server/src/config/prisma.ts
- server/src/controllers/authController.ts
- server/src/controllers/usersController.ts
- server/src/lib/generateKeyPair.ts
- server/src/middleware/authMiddleware.ts
- server/src/middleware/errorMiddleware.ts
- server/src/middleware/inputValidators.ts
- server/src/routes/auth.ts
- server/src/routes/index.ts
- server/src/routes/users.ts
- server/src/types/index.ts
- server/tsconfig.json
- Adjust backend imports to ES module and formatting
n/a
- [Jira Link](https://yassahr.atlassian.net/browse/TJN-64)
> TJN-64/ES-module

- client/src/components/profile/BookingCard.tsx
- client/src/components/profile/BookingSnippet.tsx
- client/src/pages/ProfilePage.tsx
- data in column 4 did not match our apps data looked like taxi data rather than service data
- going to profile page and seeing details for bookings new displays correct hardcoded for now for demo
- https://yassahr.atlassian.net/jira/software/projects/TJN/boards/1?selectedIssue=TJN-71
> fix 4th column values for demo

- client/db.json
- client/src/features/bookService/api/availableDatesApi.ts
- client/src/features/bookService/api/availableTechniciansApi.ts
- client/src/features/bookService/api/availableTimesApi.ts
- client/src/features/bookService/api/index.ts
- client/src/features/bookService/components/BookServiceForm.tsx
- client/src/features/bookService/hooks/index.ts
- client/src/features/bookService/hooks/useFetchAvailableTechnicians.ts
- client/src/features/bookService/hooks/useFetchAvailableTimes.ts
- client/src/features/bookService/types/Availability.ts
- client/src/features/bookService/types/TimeSlot.ts
- client/src/features/bookService/types/index.ts
- Use custom hooks to fetch data for each stage of the booking form
- Services available
- Days available for selected service
- Times available for selected day and service
- Technicians available for selected day, service, and time
- Start the mock db from client dir: ```npm run server```
- Start the frontend in another terminal: ```npm run dev```
- Click the "Book Now" link in the NavBar:
- Select a service:
- Choose a date (only dates where technicians are available can be selected from the date picker; confirm by checking db.json):
- Choose a time (only time slots available for the date should be showing; confirm with mocked db as before):
- Choose a technician (only technicians available should be showing):
- Continue filling out the form (no validation yet)
- Once the entire form …
> Tjn 56 booking to invoice feature hooks

- client/package-lock.json
- client/package.json
- client/src/features/bookService/components/BookServiceForm.tsx
- client/src/features/bookService/types/Address.ts
- Add validation to BookServiceForm and auto-scroll to end of form as user inputs values. Validation errors should only be displayed after the input changes focus (onBlur) but should disappear as soon as the input is valid.
- Add an invalid value to either address, city, or zipcode (or focus on one and move to another input without adding any value):
- Return to the invalid input and change it to a valid input:
- [Jira Link](https://yassahr.atlassian.net/browse/TJN-56)
> TJN-56-book-form-validation

- server/src/controllers/addressController.ts
- server/src/controllers/authController.ts
- server/src/middleware/authMiddleware.ts
- server/src/middleware/inputValidators.ts
- server/src/routes/users.ts
- server/src/services/addressService.ts
- server/src/services/bookingService.ts
- server/src/services/technicianService.ts
- server/src/services/userService.ts
- server/src/types/error.ts
- server/src/types/index.ts
- server/src/utils/dateUtils.ts
- Introduce Addresses related endpoints
- Add Address 
- List Addresses
- Edit Address
- Introduce user(customer/technician) profile endpoint 
- Backend will determine if the `userId` is a technician or not and will return profile info accordingly  
Reference Postman API doc: https://www.postman.com/lively-sunset-157662/neat-fleet/request/i7t876m/edit-address
under `User` section
NOTE: All following tests require the usage of `bearer token`, which can be retrieved from the request after signing in (session lasts for 2 hours) Please utilize the login credentials for Joe Swole (which can be seen in Postman's sign in request)
1. Test Adding Address with a POST request to `http://localhost:3000/api/users/addresses`
-  Check supabase to see if a specific address is there. Check doc, and you …
> TJN-32 create backend endpoints for user

- server/prisma/seed.ts
- server/src/controllers/availabilitiesController.ts
- server/src/controllers/technicianController.ts
- server/src/routes/availabilities.ts
- server/src/routes/index.ts
- server/src/routes/technician.ts
- server/src/services/technicianService.ts
- Add technician availabilities endpoints to create multiple availabilities at once and delete or update single availability
- Increased seed data values to facilitate testing
- Postman docs with endpoints and examples: https://www.postman.com/lively-sunset-157662/neat-fleet/folder/kiz2u0q/technicians?action=share&source=copy-link&creator=33600108&ctx=documentation
- Step 1 Set up local environment
- Step 2 Seed database by running ``` npm run seed ```
- Step 3 Open postman and try endpoints by providing the right IDs and data in base of your db values
- [Jira Link](https://yassahr.atlassian.net/browse/TJN-73)
> TJN-73/technician-endpoints

- server/src/controllers/bookingsController.ts
- server/src/routes/bookings.ts
- server/src/services/bookingService.ts
- Add get booking by ID endpoint
- Updated booking response to include names of technician and user
- Postman docs: https://www.postman.com/lively-sunset-157662/neat-fleet/request/uuv5o32/get-booking-by-id?action=share&source=copy-link&creator=33600108&ctx=documentation
- Step 1 Set up local environement
- Step 2 Seed local db by running ```npm run seed```
- Step 3 Open Postman and try the new endpoint
- [Jira Link](https://yassahr.atlassian.net/browse/TJN-83)
> TJN-83/update-booking-endpoints

- server/prisma/migrations/20250809091422_update_service_status_enum/migration.sql
- server/prisma/schema.prisma
update service_status from bookings table to include the following enum:
- scheduled
- on_the_way
- in_progress
- completed
- cancelled
- [s] Improvement
N/A
- [s] No documentation changes required
- [Jira Link](https://yassahr.atlassian.net/jira/software/projects/TJN/boards/1?selectedIssue=TJN-88)
> TJN-88 service-status-enum-update

- client/src/pages/LoginPage.tsx
- client/src/pages/SignupPage.tsx
- Information on what the PR is trying to achieve
- Login as existing user.  You should be redirected to the profile page or the last page you were visiting.
- Signup as new user.  You should be redirected to the profile page or the last page you were visiting.
> Add redirect to Login and Signup page

- server/src/controllers/invoicesController.ts
- server/src/middleware/inputValidators.ts
- server/src/routes/bookings.ts
- server/src/services/invoiceService.ts
This PR adds new endpoints for managing invoices linked to bookings.  
It includes:
- **POST /api/bookings/:bookingId/invoice** → Create an invoice for a booking (only accessible by the booking’s associated user).
- **GET /api/bookings/:bookingId/invoice** → Retrieve the invoice for a booking.
Additional features:
- Ownership validation to ensure only the associated user can create or view an invoice.
- Integrated input validation for `cost` and `tax_percent` values.
- Proper HTTP status codes for unauthorized, forbidden, not found, and successful requests.
NOTE: reference https://www.postman.com/lively-sunset-157662/neat-fleet/folder/rb5xfsq/invoices for more details
- **Precondition:** You must be logged in as the **user associated with the booking** (technicians cannot generate …
> TJN 90 add invoice endpoint

- client/src/features/bookService/components/BookServiceForm.tsx
- client/src/routes/routes.tsx
- Redirect user to booking form if user clicks the "Sign in to Reserve" button at end of form.  Otherwise redirect to ProfilePage
- Login and confirm redirect to Profile
- Logout and fill out the Book Service form all they way to the "Sign in to Reserve" button
- Confirm that login redirects back to Book Service form
- [Jira Link](https://yassahr.atlassian.net/browse/TJN-103)
> Tjn 103 reserve and pay redirects to homepage after entering credentials

- client/package-lock.json
- client/package.json
- client/src/features/auth/components/LoginForm.tsx
- client/src/features/auth/components/SignupForm.tsx
- client/src/features/auth/hooks/useLogout.ts
- client/src/layouts/MainLayout.tsx
- client/src/lib/utils.ts
- Add toast messages for login/signup/logout
- Step 1 Set up local environment
- Step 2 Try login/signup/logout and ensure the toasts are showing up
- [Jira Link](https://yassahr.atlassian.net/browse/TJN-104)
> TJN-104/toast-notifications

- client/src/components/Footer.tsx
- client/src/components/NavBar.tsx
- client/src/components/home/AboutSection.tsx
- client/src/components/home/HomeScreen.tsx
- client/src/components/home/Location.tsx
- client/src/components/home/Services.tsx
- server/src/controllers/bookingsController.ts
I added a new logo for Neat Fleet and updated some content on the main page
- Step 1
Navigate to the main page and bask in the glory of the new logo. Also check out the footer. I re-added the about page for the team.
- [Jira Link](https://yassahr.atlassian.net/jira/software/projects/TJN/boards/1)
> TJN-97 New Logo
